#version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db_ks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env


  redis:
    image: redis:latest
    container_name: redis_ks
    ports:
      - "6379:6379"


  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin
    ports:
      - "8080:80"
    env_file:
      - .env


  web:
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileKS
      args:
        - --no-cache
    container_name: web
    volumes:
      - ../keysystems_web:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailhog
    env_file:
      - .env


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d/base.conf:/etc/nginx/conf.d/base.conf
#      - ../ssl:/etc/nginx/ssl
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web


volumes:
  postgres_data:
  static_value:
  media_value:

